# Generated by Django 5.0.1 on 2024-03-11 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectricityConsumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=200)),
                ("connection_number", models.CharField(max_length=20, unique=True)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("connection_date", models.DateField(auto_now_add=True)),
                ("status", models.IntegerField()),
                ("lastupdate", models.DateTimeField(auto_now=True)),
                ("password", models.CharField(max_length=26)),
            ],
        ),
        migrations.CreateModel(
            name="KSEBOffice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("phone_number", models.CharField(max_length=15)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("office_code", models.CharField(max_length=20, unique=True)),
                ("password", models.CharField(max_length=26)),
            ],
        ),
    ]
