# Generated by Django 5.0.1 on 2024-03-11 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="electricityconsumer",
            name="office_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Admin.kseboffice",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="kseboffice",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
