# Generated by Django 5.0.1 on 2024-03-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0002_electricityconsumer_office_id_alter_kseboffice_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electricityconsumer",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
