# Generated by Django 5.0.1 on 2024-03-13 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0003_alter_electricityconsumer_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authority", models.IntegerField()),
                ("msg", models.CharField(max_length=250)),
                ("view_sts", models.IntegerField()),
                ("direction", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.electricityconsumer",
                    ),
                ),
            ],
        ),
    ]
