# Generated by Django 5.0.1 on 2024-03-13 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0004_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annoucement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("msg", models.CharField(max_length=250)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.kseboffice",
                    ),
                ),
            ],
        ),
    ]
