# Generated by Django 5.0.1 on 2024-03-28 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0005_annoucement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("kwh", models.CharField(max_length=25)),
                ("rate", models.FloatField()),
                ("month", models.CharField(max_length=25)),
                ("BillGenerationdate", models.DateField(auto_now_add=True)),
                ("paymentDate", models.DateTimeField(auto_now=True)),
                ("status", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Admin.electricityconsumer",
                    ),
                ),
            ],
        ),
    ]
