# Generated by Django 5.0.1 on 2024-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Admin", "0006_bill"),
    ]

    operations = [
        migrations.AddField(
            model_name="bill",
            name="file",
            field=models.FileField(blank=True, upload_to="uploads/bills"),
        ),
        migrations.AlterField(
            model_name="bill",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
